[build]

command = "yarn run prod; ./vendor/bin/jigsaw build production"
publish = "build_production"
environment = { PHP_VERSION = "7.4", NODE_VERSION = "15" }

[template.environment]
  BASE_URL_STAGING = "stage.buffermint.com"
  BASE_URL_PRODUCTION = "buffermint.com"