[build]

command = "./vendor/bin/jigsaw build production && npm run prod"
publish = "build_production"
environment = { PHP_VERSION = "7.4", NODE_VERSION = "11" }

[template.environment]
  BASE_URL_STAGING = "stage.buffermint.com"
  BASE_URL_PRODUCTION = "buffermint.com"