[build]

command = "npm run production"
publish = "build_production"
environment = { PHP_VERSION = "7.2", NODE_VERSION = "11" }

[template.environment]
  BASE_URL_STAGING = "stage.buffermint.com"
  BASE_URL_PRODUCTION = "buffermint.com"